name: Release Build

on:
  push:
    tags:
      - '*.*.*.*-*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            script-id: [win32]
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          env:
            FILE_ENV: ./ci/test/00_setup_env_{{ matrix.script-id }}.sh
            OS_NAME: linux
          run: |
            ./cd/release.sh
      - name: cache
        uses: actions/cache@v2
        with:
        path: |
            ./depends/built
            ./ci/scratch/.ccache
        key: ${{ runner.os }}-${{ matrix.script-id }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/*
