name: Ubuntu Build (Bionic, latest libdb from repo)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: apt update & install depends
      run: sudo apt-get update && sudo apt-get install libqt5gui5 libqt5core5a qtbase5-dev libqt5dbus5 qttools5-dev qttools5-dev-tools libqt5charts5-dev libssl-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-iostreams-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libminiupnpc-dev protobuf-compiler libqrencode-dev xvfb libzip4 libzip-dev zlib1g zlib1g-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-incompatible-bdb --with-gui=qt5
    - name: make distdir
      run: make distdir VERSION=x86_64-unknown-linux-gnu
    - name: make
      run: make
