name: Ubuntu Build (Bionic, x86_64, template)

on: [push, pull_request]

jobs:
  build:
    env:
      CCACHE_SIZE: 250M
      CCACHE_TEMPDIR: /tmp/.ccache-temp
      CCACHE_COMPRESS: 1
      MAKEJOBS: -j3
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: flags
      uses: ./.github/actions/
      with:
        host: x86_64-unknown-linux-gnu
      id: actions
    - name: ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ github.repository }}-ccache-${{ github.run_id }}
        restore-keys: |
          ${{ github.repository }}-ccache-
    - name: apt update & install depends
      run: sudo apt-get update && sudo apt-get install ${{ steps.actions.outputs.pkgmgnrdepends }}
    - name: autogen
      run: ./autogen.sh  
    - name: configure
      run: ./configure --cache-file=config.cache ${{ steps.actions.outputs.config }} || ( cat config.log && false)
    - name: make distdir
      run: make distdir VERSION=x86_64-unknown-linux-gnu
    #- name: configure again
    #  run: cd gridcoin-$HOST && ./configure --cache-file=../config.cache --disable-dependency-tracking --with-incompatible-bdb --with-gui=qt5 --enable-reduce-export || ( cat config.log && false)
    - name: make install
      run: sudo make $MAKEJOBS install || ( echo "Build failure. Verbose build follows." && sudo make install V=1 ; false )
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: make check
      run: make $MAKEJOBS check VERBOSE=1