name: Ubuntu Build (Bionic, latest libdb from repo)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: install depends
      run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libdb-dev libdb++-dev libzip-dev libqt5* libqrencode-dev libboost-all-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-incompatible-bdb --with-gui=qt5
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
