name: Ubuntu Build (Bionic, x86_64)

on: [push, pull_request]

jobs:
  build:
    env:
      CCACHE_SIZE: 250M
      CCACHE_TEMPDIR: /tmp/.ccache-temp
      CCACHE_COMPRESS: 1
      MAKEJOBS: -j3
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
    - name: ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ github.repository }}-ccache-${{ github.run_id }}
        restore-keys: |
          ${{ github.repository }}-ccache-
    - name: apt update & install depends
      run: sudo apt-get update && sudo apt-get install ccache libqt5gui5 libqt5core5a qtbase5-dev libqt5dbus5 qttools5-dev qttools5-dev-tools libqt5charts5-dev libssl-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-iostreams-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libminiupnpc-dev protobuf-compiler libqrencode-dev xvfb libzip4 libzip-dev zlib1g zlib1g-dev libcurl4-gnutls-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --cache-file=config.cache --disable-dependency-tracking --with-incompatible-bdb --with-gui=qt5 --enable-reduce-export || ( cat config.log && false)
    - name: make distdir
      run: make distdir VERSION=x86_64-unknown-linux-gnu
    - name: make install
      run: sudo make $MAKEJOBS install || ( echo "Build failure. Verbose build follows." && sudo make install V=1 ; false )
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: make check
      run: make $MAKEJOBS check VERBOSE=1