name: Ubuntu Build (Bionic, latest libdb from repo)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install depends
      run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libdb-dev libdb++-dev
    - name: install boost depends
      run: sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libboost-iostreams-dev libcurl4-gnutls-dev
    - name: install gui depends
      run: sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-incompatible-bdb
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
