name: Windows (64 Bit)

on: [push, pull_request]

jobs:
  build:
    env:
      CCACHE_SIZE: 250M
      CCACHE_TEMPDIR: /tmp/.ccache-temp
      CCACHE_COMPRESS: 1
      MAKEJOBS: -j3
      HOST: x86_64-w64-mingw32
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: add to path
      run: export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
    - name: ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ github.repository }}-ccache-${{ github.run_id }}
        restore-keys: |
          ${{ github.repository }}-ccache-
    - name: cache depends
      uses: actions/cache@v1
      with:
        path: depends/built
        key: ${{ github.repository }}-depends-${{ github.run_id }}
        restore-keys: |
          ${{ github.repository }}-depends-
    - name: apt update & install depends
      run: sudo apt-get update && sudo dpkg --add-architecture "i386" && sudo apt-get install ccache python3 nsis g++-mingw-w64-x86-64
    - name: update alternatives
      run:  sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - name: build depends
      run: make $MAKEJOBS -C depends HOST=$HOST NO_QT=1
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --cache-file=config.cache --disable-dependency-tracking --with-incompatible-bdb --with-gui=qt5 --enable-reduce-export --prefix=depends/$HOST|| ( cat config.log && false)
    - name: make distdir
      run: make distdir VERSION=$HOST
    - name: make
      run: make $MAKEJOBS || ( echo "Build failure. Verbose build follows." && make V=1 ; false )
