name: Windows (64 Bit)

on: [push, pull_request]

jobs:
  build:
    env:
      CCACHE_SIZE: 100M
      CCACHE_TEMPDIR: /tmp/.ccache-temp
      CCACHE_COMPRESS: 1
      MAKEJOBS: -j3
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ github.repository }}-ccache
    - name: add arch
      run: sudo dpkg --add-architecture "i386" && sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - name: apt update & install depends
      run: sudo apt-get update && sudo apt-get install ccache python3 nsis g++-mingw-w64-x86-64
    - name: build depends
      run: make $MAKEJOBS -C depends HOST=x86_64-w64-mingw32 NO_QT=1
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --cache-file=config.cache --disable-dependency-tracking --with-incompatible-bdb --with-gui=qt5 --enable-reduce-export  || ( cat config.log && false)
    - name: make distdir
      run: make distdir VERSION=x86_64-w64-mingw32
    - name: make
      run: make $MAKEJOBS || ( echo "Build failure. Verbose build follows." && make V=1 ; false )
